import type { Pilar, Skill } from "./types";

export const PILARES: { pilar: Pilar; label: string; color: string }[] = [
  { pilar: "fuerza", label: "Fuerza", color: "#6934E1" },
  { pilar: "gimnasia", label: "Gimnasia y Acrobacias", color: "#F59E0B" },
  { pilar: "resistencia", label: "Resistencia", color: "#10B981" },
  { pilar: "constancia", label: "Constancia La Terraza", color: "#EC4899" },
];

type SkillSeed = Omit<Skill, "id" | "activa">;

export const CATALOGO_MEDALLAS: SkillSeed[] = [
  // ---------- Pilar 1 — Fuerza (niveles, relativos a BW) ----------
  {
    pilar: "fuerza",
    nombreMedalla: "Peso Muerto",
    habilidad: "Deadlift",
    tipo: "niveles",
    nivelesDisponibles: ["bronce", "plata", "oro"],
    hitos: { bronce: "1", plata: "1.5", oro: "2" },
    relativoABW: true,
    orden: 1,
    arte: "peso-muerto",
  },
  {
    pilar: "fuerza",
    nombreMedalla: "Sentadilla Trasera",
    habilidad: "Back Squat",
    tipo: "niveles",
    nivelesDisponibles: ["bronce", "plata", "oro"],
    hitos: { bronce: "1", plata: "1.25", oro: "1.5" },
    relativoABW: true,
    orden: 2,
    arte: "sentadilla-trasera",
  },
  {
    pilar: "fuerza",
    nombreMedalla: "Sentadilla Frontal",
    habilidad: "Front Squat",
    tipo: "niveles",
    nivelesDisponibles: ["bronce", "plata", "oro"],
    hitos: { bronce: "0.75", plata: "1", oro: "1.25" },
    relativoABW: true,
    orden: 3,
    arte: "sentadilla-frontal",
  },
  {
    pilar: "fuerza",
    nombreMedalla: "Press Estricto",
    habilidad: "Press Estricto",
    tipo: "niveles",
    nivelesDisponibles: ["bronce", "plata", "oro"],
    hitos: { bronce: "0.35", plata: "0.5", oro: "0.75" },
    relativoABW: true,
    orden: 4,
    arte: "press-estricto",
  },
  {
    pilar: "fuerza",
    nombreMedalla: "Clean",
    habilidad: "Cargada",
    tipo: "niveles",
    nivelesDisponibles: ["bronce", "plata", "oro"],
    hitos: { bronce: "tecnica", plata: "0.75", oro: "1" },
    relativoABW: true,
    orden: 5,
    arte: "clean",
  },
  {
    pilar: "fuerza",
    nombreMedalla: "Snatch",
    habilidad: "Arranque",
    tipo: "niveles",
    nivelesDisponibles: ["bronce", "plata", "oro"],
    hitos: { bronce: "tecnica", plata: "0.5", oro: "0.75" },
    relativoABW: true,
    orden: 6,
    arte: "snatch",
  },
  {
    pilar: "fuerza",
    nombreMedalla: "Clean & Jerk",
    habilidad: "Clean & Jerk",
    tipo: "niveles",
    nivelesDisponibles: ["bronce", "plata", "oro"],
    hitos: { bronce: "tecnica", plata: "0.75", oro: "1" },
    relativoABW: true,
    orden: 7,
    arte: "clean-jerk",
  },
  {
    pilar: "fuerza",
    nombreMedalla: "Club de las 300 lbs",
    habilidad: "Peso muerto o sentadilla",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "Peso muerto o sentadilla ≥ 300 lbs (136 kg)" },
    relativoABW: false,
    orden: 8,
    arte: "club-300",
  },
  {
    pilar: "fuerza",
    nombreMedalla: "Overhead",
    habilidad: "Overhead Squat",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "Primera overhead squat con técnica validada" },
    relativoABW: false,
    orden: 9,
    arte: "overhead",
  },

  {
    pilar: "fuerza",
    nombreMedalla: "Thruster",
    habilidad: "Thruster",
    tipo: "niveles",
    nivelesDisponibles: ["bronce", "plata", "oro"],
    hitos: { bronce: "tecnica", plata: "0.6", oro: "0.85" },
    relativoABW: true,
    orden: 10,
    arte: "thruster",
  },
  {
    pilar: "fuerza",
    nombreMedalla: "Push Jerk",
    habilidad: "Push Jerk",
    tipo: "niveles",
    nivelesDisponibles: ["bronce", "plata", "oro"],
    hitos: { bronce: "tecnica", plata: "0.65", oro: "0.9" },
    relativoABW: true,
    orden: 11,
    arte: "push-jerk",
  },

  // ---------- Pilar 2 — Gimnasia y Acrobacias (insignias) ----------
  {
    pilar: "gimnasia",
    nombreMedalla: "Equilibrio",
    habilidad: "Handstand hold",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "Sostener 30 segundos contra pared" },
    relativoABW: false,
    orden: 1,
    arte: "equilibrio",
  },
  {
    pilar: "gimnasia",
    nombreMedalla: "Caminante",
    habilidad: "Handstand walk",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "Caminar 5 metros de manos" },
    relativoABW: false,
    orden: 2,
    arte: "caminante",
  },
  {
    pilar: "gimnasia",
    nombreMedalla: "Primera Cima",
    habilidad: "Pull-up",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "Primera dominada estricta" },
    relativoABW: false,
    orden: 3,
    arte: "primera-cima",
  },
  {
    pilar: "gimnasia",
    nombreMedalla: "Vuelo",
    habilidad: "Kipping / butterfly pull-ups",
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "10 kipping pull-ups seguidas", oro: "10 butterfly pull-ups seguidas" },
    relativoABW: false,
    orden: 4,
    arte: "vuelo",
  },
  {
    pilar: "gimnasia",
    nombreMedalla: "Gravedad",
    habilidad: "Muscle-up",
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "Tu primer muscle-up (barra)", oro: "Muscle-up en anillas" },
    relativoABW: false,
    orden: 5,
    arte: "gravedad",
  },
  {
    pilar: "gimnasia",
    nombreMedalla: "Invertido",
    habilidad: "Handstand push-up",
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "Primera HSPU", oro: "HSPU estricta" },
    relativoABW: false,
    orden: 6,
    arte: "invertido",
  },
  {
    pilar: "gimnasia",
    nombreMedalla: "Escalador",
    habilidad: "Rope climb",
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "Subida completa de soga", oro: "Subida sin piernas" },
    relativoABW: false,
    orden: 7,
    arte: "escalador",
  },
  {
    pilar: "gimnasia",
    nombreMedalla: "Pistolero",
    habilidad: "Pistol squat",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "1 pistol squat por pierna" },
    relativoABW: false,
    orden: 8,
    arte: "pistolero",
  },
  {
    pilar: "gimnasia",
    nombreMedalla: "Núcleo",
    habilidad: "Toes-to-bar / L-sit",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "5 toes-to-bar seguidas o L-sit 15 segundos" },
    relativoABW: false,
    orden: 9,
    arte: "nucleo",
  },

  {
    pilar: "gimnasia",
    nombreMedalla: "Dips",
    habilidad: "Dips en anillas",
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "3 dips estrictos en anillas", oro: "10 dips en anillas seguidos" },
    relativoABW: false,
    orden: 10,
    arte: "dips",
  },
  {
    pilar: "gimnasia",
    nombreMedalla: "Volar",
    habilidad: "Box jump",
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "Box jump 50 cm (hombre) / 40 cm (mujer)", oro: "Box jump 75 cm (hombre) / 60 cm (mujer)" },
    relativoABW: false,
    orden: 11,
    arte: "volar",
  },

  // ---------- Pilar 3 — Resistencia ----------
  {
    pilar: "resistencia",
    nombreMedalla: "Ninja",
    habilidad: "Double unders",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "50 saltos dobles seguidos" },
    relativoABW: false,
    orden: 1,
    arte: "ninja",
  },
  {
    pilar: "resistencia",
    nombreMedalla: "Primer Doble",
    habilidad: "Double unders",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "Tu primer salto doble" },
    relativoABW: false,
    orden: 2,
    arte: "primer-doble",
  },
  {
    pilar: "resistencia",
    nombreMedalla: "Héroe",
    habilidad: 'WOD "Murph"',
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "Completar el Murph entero", oro: "Completarlo con chaleco" },
    relativoABW: false,
    orden: 3,
    arte: "heroe",
  },
  {
    pilar: "resistencia",
    nombreMedalla: "Fran",
    habilidad: 'WOD benchmark "Fran"',
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "Completar Fran", oro: "Completarla en menos de 8 minutos" },
    relativoABW: false,
    orden: 4,
    arte: "fran",
  },
  {
    pilar: "resistencia",
    nombreMedalla: "Motor",
    habilidad: "Remo",
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "2 km completos en remo", oro: "2 km en menos de 8 minutos" },
    relativoABW: false,
    orden: 5,
    arte: "motor",
  },
  {
    pilar: "resistencia",
    nombreMedalla: "RX",
    habilidad: "Cualquier WOD",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "Primer WOD completado con pesos y movimientos prescritos" },
    relativoABW: false,
    orden: 6,
    arte: "rx",
  },

  {
    pilar: "resistencia",
    nombreMedalla: "Annie",
    habilidad: 'WOD benchmark "Annie"',
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "Completar Annie (50-40-30-20-10)", oro: "Completarla en menos de 12 minutos" },
    relativoABW: false,
    orden: 7,
    arte: "annie",
  },
  {
    pilar: "resistencia",
    nombreMedalla: "Cindy",
    habilidad: 'WOD benchmark "Cindy"',
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "Completar Cindy (20 min AMRAP)", oro: "Completar 20+ rondas" },
    relativoABW: false,
    orden: 8,
    arte: "cindy",
  },
  {
    pilar: "resistencia",
    nombreMedalla: "Corredor/a",
    habilidad: "Carrera",
    tipo: "insignia",
    nivelesDisponibles: ["base", "oro"],
    hitos: { base: "Completar 5 km", oro: "Completar 5 km en menos de 25 minutos" },
    relativoABW: false,
    orden: 9,
    arte: "corredor",
  },

  // ---------- Pilar 4 — Constancia (automáticas, Cloud Function) ----------
  {
    pilar: "constancia",
    nombreMedalla: "Mes Perfecto",
    habilidad: "Asistencia",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "100% de asistencia en un mes" },
    relativoABW: false,
    orden: 1,
    arte: "mes-perfecto",
  },
  {
    pilar: "constancia",
    nombreMedalla: "Centenaria/o",
    habilidad: "Asistencia",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "100 clases asistidas" },
    relativoABW: false,
    orden: 2,
    arte: "centenaria",
  },
  {
    pilar: "constancia",
    nombreMedalla: "Un Año en La Terraza",
    habilidad: "Antigüedad",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "Aniversario en el box" },
    relativoABW: false,
    orden: 3,
    arte: "un-anio",
  },
  {
    pilar: "constancia",
    nombreMedalla: "Fundador/a",
    habilidad: "Antigüedad",
    tipo: "insignia",
    nivelesDisponibles: ["base"],
    hitos: { base: "Estar entre los primeros alumnos de la app" },
    relativoABW: false,
    orden: 4,
    arte: "fundador",
  },
];
